import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { IBM_Plex_Sans } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from "@/components/Footer";
import CheckIcon from '@mui/icons-material/Check';
import { Carousel } from '@mantine/carousel';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { DateCalendar } from '@mui/x-date-pickers/DateCalendar';
import {
    Grid,
    Typography,
    useMediaQuery,
    Box,
    Button,
    Icon,
    Avatar, List, Divider
} from '@mui/material';
import * as url from "url";
import { createTheme, ThemeProvider} from "@mui/material";
import PriceDesktop from "@/components/PriceDesktop";
import PriceMobile from "@/components/PriceMobile";
import Header2 from "@/components/Header2";

const inter = Inter({ subsets: ['latin'] })
const IBM = IBM_Plex_Sans( { weight: "600", subsets: ['latin'] } )


export default function Home() {
    let isDesktop = useMediaQuery('(max-width:1400px)');
    let isMobile = useMediaQuery('(max-width:1000px)');

    return (
        <>
            <Head>
                <title>Optimized Horizons</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Header2 />
                {!isMobile && <PriceDesktop />}
                {isMobile && <PriceMobile />}



                    <Footer />



            </main>
        </>
    )
}